# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest
variables:
  working-dir: 'maven-examples-myyong/maven-mutation-testing'
steps:
- task: JFrogMaven@1
  inputs:
    workingDirectory: $(working-dir)
    mavenPomFile: 'pom.xml'
    goals: 'install'
    artifactoryResolverService: 'adoptionplus'
    targetResolveReleaseRepo: 'azuremvn-libs-release'
    targetResolveSnapshotRepo: 'azuremvn-libs-snapshot'
    artifactoryDeployService: 'adoptionplus'
    targetDeployReleaseRepo: 'azuremvn-libs-release'
    targetDeploySnapshotRepo: 'azuremvn-libs-snapshot'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    javaHomeOption: 'JDKVersion'
- task: JFrogPublishBuildInfo@1
  inputs:
    artifactoryConnection: 'adoptionplus'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    
        
