# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest
variables:
  working-dir: 'maven-examples-myyong/maven-mutation-testing'
  
steps:
- checkout: self
- task: Bash@3
  displayName: 'Diagnose: List Source Directory Contents'
  inputs:
    targetType: 'inline'
    script: |
      echo "Current working directory on agent: $(pwd)"
      echo "Build.SourcesDirectory: $(Build.SourcesDirectory)"
      echo "--- Contents of $(Build.SourcesDirectory) ---"
      ls -R $(Build.SourcesDirectory) # Recursively list all files and folders
      echo "--- End of listing ---"

- task: JFrogCLI@2
  displayName: 'Build and Publish with JFrog CLI'
  inputs:
    jfrogService: 'YourServiceConnectionName' # Make sure this is correct
    command: 'jf mvn install -f "$(Build.SourcesDirectory)/pom.xml" --build-name="UmaChintala.maven-examples-myyong" --build-number="$(Build.BuildNumber)"'
- task: JFrogMaven@1
  inputs:
    workingDirectory: $(working-dir)
    mavenPomFile: 'pom.xml'
    goals: 'install'
    artifactoryResolverService: 'adoptionplus'
    targetResolveReleaseRepo: 'azuremvn-libs-release'
    targetResolveSnapshotRepo: 'azuremvn-libs-snapshot'
    artifactoryDeployService: 'adoptionplus'
    targetDeployReleaseRepo: 'azuremvn-libs-release'
    targetDeploySnapshotRepo: 'azuremvn-libs-snapshot'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    javaHomeOption: 'JDKVersion'
- task: JFrogPublishBuildInfo@1
  inputs:
    artifactoryConnection: 'adoptionplus'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    
        
